[package]
name = "cat-recognition"
authors = ["Igor Karpenko <chifmaster113@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"